input_dir: TopTagger
output_dir: trainedTopTagger
model_name: GlobalClassifier
loss_name: GlobalLoss
loss_pars: 1, 1

batch_size: 100
num_iters: 8
learning_rate: 0.0005
num_epochs: 10
stop_on: "auc"
patiences: 10
log_freq: 100
val_batches: 50