input_dir: inputs
evts_per_file: 10
output_dir: WjetsTrained
model: EdgeClassifier
loss_name: EdgeLoss
loss_pars: 2, 1

learning_rate: 0.001
batch_size: 1
num_epochs: 3
num_iters: 4
stop_on: "auc"
patiences: 3
log_freq: 5
val_batches: 2