input_dir: LeadingJets
output_dir:  WvsQCDLeadingJets
model: GlobalClassifier
loss_name: GlobalLoss
loss_pars: 1, 1

batch_size: 1
num_iters: 8
learning_rate: 0.0005
num_epochs: 10
stop_on: "auc"
patiences: 10
log_freq: 5
val_batches: 2