electrons:
  - el_pt
  - el_eta
  - el_phi
  - el_e
muons:
  - mu_pt
  - mu_eta
  - mu_phi
  - mu_e
jets:
  - jet_pt
  - jet_eta
  - jet_phi
  - jet_e
NODE_ORDERS: 
  - electrons
  - muons 
  - jets 
TRUTH: 
  #- 1
  - met_met
FILTER:
  - electrons:
    - el_pt > 20
    - el_eta > 0 
    - el_pt + el_eta > 0 
  - muons:
    - mu_e > 0

# electrons:
#   - el_pt
#   - el_eta
#   - el_phi
#   - el_e
# muons:
#   - mu_pt
#   - mu_eta
#   - mu_phi
#   - mu_e
# jets:
#   - jet_pt
#   - jet_eta
#   - jet_phi
#   - jet_e
# target: #can be a list, OR could be a branch_name that contains truth information that the model is trying to predict (like predicting the properties of the higgs)
#   - 1 # or 0 