input_dir: /global/u1/l/lreed/tfrec/v1/split
evts_per_file: 1000
output_dir: /global/u1/l/lreed/trained-results/v1-results
model: GlobalClassifier
loss_name: GlobalLoss
loss_pars: 1, 1

batch_size: 100
num_iters: 4 
learning_rate: 0.0005
num_epochs: 100
stop_on: "auc"
patiences: 20
log_freq: 20
val_batches: 100
shuffle_size: 80000
dropout_rate: 0.0
