tfrec_dir_train: /global/cscratch1/sd/xju/WbosonTagger/tfrec_bigger/*_0.tfrec
tfrec_dir_val: /global/cscratch1/sd/xju/WbosonTagger/tfrec_val_bigger/*_95.tfrec
output_dir:  /global/cscratch1/sd/xju/WbosonTagger/trained
prod_name: TESTSummary
model_name: EdgeClassifier
loss_name: EdgeLoss, 2, 1
parameters:
    batch_size: 1
    n_iters: 5
    learning_rate: 0.0001
    epochs: 2
    earlystop_metric: "auc_te" #auc_te, acc_te, pre_te, rec_te
    acceptable_failure: 5
    do_profiling: true
    profiling_steps: 1000
    do_profiling_only: true
