tfrec_dir_train: /global/homes/x/xju/work/TopTagger/tfrec/*_0.tfrec
tfrec_dir_val: /global/homes/x/xju/work/TopTagger/tfrec_val/*_0.tfrec
output_dir: /global/homes/x/xju/work/TopTagger/trained
prod_name: noedge_fullevts
model_name: GlobalClassifierNoEdgeInfo
parameters:
    batch_size: 50
    n_iters: 10
    learning_rate: 0.0005
    real_weight: 1.
    fake_weight: 1.
    epochs: 20