tfrec_dir_train: /global/homes/x/xju/work/TopReco/tthyy/inputs/train/ttH_1*
tfrec_dir_val: /global/homes/x/xju/work/TopReco/tthyy/inputs/val/*
output_dir:  /global/homes/x/xju/work/TopReco/tthyy/trained
<<<<<<< HEAD
prod_name: test4
=======
prod_name: test6
>>>>>>> 0d4b8de990b66fa12ce38076f0eea1efb808113d
model_name: FourTopPredictor # don't change!
parameters:
    batch_size: 500
    learning_rate: 0.001
    epochs: 24
    earlystop_metric: "auc_te" #auc_te, acc_te, pre_te, rec_te
    acceptable_failure: 5
    num_iters: 8
    shuffle_buffer_size: 2